"""
LISTS
"""

bikeList = [
    'Alpine Trail E2',
    'Alpine Trail E1',
    'Alpine Trail Carbon 2',
    'Alpine Trail Carbon 1',
    'Alpine Trail XR',
    'Alpine Trail 7',
    'Alpine Trail Carbon 2 Frame Kit',
    'Rift Zone 29\" Carbon XR',
    'Rift Zone 29\" Carbon 2',
    'Rift Zone 29\" Carbon 1',
    'Rift Zone 29\" 3',
    'Rift Zone 29\" 2',
    'Rift Zone 29\" 1',
    'Rift Zone 29\" Carbon XR Frame Kit',
    'Rift Zone 27.5\" 3',
    'Rift Zone 27.5\" 2',
    'Rift Zone 27.5\" 1',
    'Rift Zone 26\"',
    'El Roy',
    'El Roy Frame Kit',
    'San Quentin 3',
    'San Quentin 2',
    'San Quentin 1',
    'San Quentin 3 Frame Kit',
    'Alcatraz',
    'Alcatraz Frame Kit',
    'Bolinas Ridge 2',
    'Bolinas Ridge 1',
    'Bobcat Trail 5',
    'Bobcat Trail 4',
    'Bobcat Trail 3',
    'Wildcat Trail 3',
    'Wildcat Trail 1',
    'Team Marin 2',
    'Team Marin 1',
    'Pine Mountain E2',
    'Pine Mountain E1',
    'Pine Mountain 2',
    'Pine Mountain 1',
    'Headlands 2',
    'Headlands 1',
    'Headlands Frame Kit',
    'Gestalt X11',
    'Gestalt X10',
    'Gestalt 2.5',
    'Gestalt 2',
    'Gestalt 1',
    'Gestalt',
    'DSX FS',
    'DSX 2',
    'DSX 1',
    'DSX',
    'Nicasio 2',
    'Nicasio',
    'Nicasio +',
    'Lombard 1',
    'Four Corners',
    'Muirwoods',
    'Muirwoods RC',
    'Presidio 3',
    'Presidio 2',
    'Presidio 1',
    'Fairfax 3',
    'Fairfax 2',
    'Fairfax ST 2',
    'Fairfax 1',
    'Fairfax ST 1',
    'San Rafael DS2',
    'San Rafael DS1',
    'San Anselmo DS2',
    'San Anselmo DS1',
    'Sausalito 2',
    'Sausalito ST 2',
    'Sausalito 1',
    'Sausalito ST 1',
    'Kentfield 2',
    'Kentfield ST 2',
    'Kentfield 1',
    'Kentfield ST 1',
    'Larkspur 2',
    'Larkspur 1',
    'Stinson 2',
    'Stinson ST 2',
    'Stinson 1',
    'Stinson ST 1',
    'Stinson Electric',
    'Stinson Electric ST',
    'Rift Zone Jr 24',
    'Bayview Trail 24',
    'Hidden Canyon 20',
    'San Quentin 24',
    'San Quentin 20',
]

bikeListNew = [
    'Rift Zone 29\" Carbon XR',
    'Rift Zone 29\" Carbon 2',
    'Rift Zone 29\" Carbon 1',
    'Rift Zone 29\" Carbon XR Frame Kit',
    'Alcatraz',
    'Alcatraz Frame Kit'
    'Bolinas Ridge 2',
    'Bobcat Trail 4',
    'Bobcat Trail 5',
    'Wildcat Trail 3',
    'Wildcat Trail 1',
    'Headlands 2',
    'Gestalt 2.5',
    'DSX FS',
    'DSX',
    'Muirwoods',
    'Fairfax 3',
    'Fairfax 2',
    'Fairfax ST 2',
    'Fairfax 1',
    'Fairfax ST 1',
    'Stinson Electric',
    'Stinson Electric ST',
    
]

bikeListCopy = [
    'Alpine Trail E2',
    'Alpine Trail E1',
    'Alpine Trail Carbon 2',
    'Alpine Trail Carbon 1',
    'Alpine Trail XR',
    'Alpine Trail 7',
    'Alpine Trail Carbon 2 Frame Kit',
    'Rift Zone 29\" 3',
    'Rift Zone 29\" 2',
    'Rift Zone 29\" 1',
    'Rift Zone 27.5\" 3',
    'Rift Zone 27.5\" 2',
    'Rift Zone 27.5\" 1',
    'El Roy',
    'El Roy Frame Kit',
    'San Quentin 3',
    'San Quentin 2',
    'San Quentin 1',
    'San Quentin 3 Frame Kit',
    'Alcatraz Frame Kit',
    'Bolinas Ridge 1',
    'Bobcat Trail 3',
    'Team Marin 2',
    'Team Marin 1',
    'Pine Mountain E2',
    'Pine Mountain E1',
    'Pine Mountain 2',
    'Pine Mountain 1',
    'Headlands 1',
    'Headlands Frame Kit',
    'Gestalt X11',
    'Gestalt X10',
    'Gestalt 2',
    'Gestalt 1',
    'Gestalt',
    'DSX 2',
    'DSX 1',
    'Nicasio 2',
    'Nicasio 1',
    'Nicasio +',
    'Lombard 1',
    'Four Corners',
    'Muirwoods RC',
    'Presidio 3',
    'Presidio 2',
    'Presidio 1',
    'San Rafael DS2',
    'San Rafael DS1',
    'San Anselmo DS2',
    'San Anselmo DS1',
    'Sausalito 2',
    'Sausalito ST 2',
    'Sausalito 1',
    'Sausalito ST 1',
    'Kentfield 2',
    'Kentfield ST 2',
    'Kentfield 1',
    'Kentfield ST 1',
    'Larkspur 2',
    'Larkspur 1',
    'Stinson 2',
    'Stinson ST 2',
    'Stinson 1',
    'Stinson ST 1',
    'Rift Zone 26',
    'Rift Zone Jr 24',
    'Bayview Trail 24',
    'Hidden Canyon 20',
    'San Quentin 24',
    'San Quentin 20',
]

bikeListCopy_Slugs = [
    'Alpine-Trail-E2',
    'Alpine-Trail-E1',
    'Alpine-Trail-Carbon-2',
    'Alpine-Trail-Carbon-1',
    'Alpine-Trail-XR',
    'Alpine-Trail-7',
    'Alpine-Trail-Carbon-2-Frame-Kit',
    'Rift-Zone-29-3',
    'Rift-Zone-29-2',
    'Rift-Zone-29-1',
    'Rift-Zone-27.5-3',
    'Rift-Zone-27.5-2',
    'Rift-Zone-27.5-1',
    'El-Roy',
    'El-Roy-Frame-Kit',
    'San-Quentin-3',
    'San-Quentin-2',
    'San-Quentin-1',
    'San-Quentin-3-Frame-Kit',
    'Alcatraz-Frame-Kit',
    'Bolinas-Ridge-1',
    'Bobcat-Trail-3',
    'Team-Marin-2',
    'Team-Marin-1',
    'Pine-Mountain-E2',
    'Pine-Mountain-E1',
    'Pine-Mountain-2',
    'Pine-Mountain-1',
    'Headlands-1',
    'Headlands-Frame-Kit',
    'Gestalt-X11',
    'Gestalt-X10',
    'Gestalt-2',
    'Gestalt-1',
    'Gestalt',
    'DSX-2',
    'DSX-1',
    'Nicasio-2',
    'Nicasio-1',
    'Nicasio-plus',
    'Lombard-1',
    'Four-Corners',
    'Muirwoods-RC',
    'Presidio-3',
    'Presidio-2',
    'Presidio-1',
    'San-Rafael-DS2',
    'San-Rafael-DS1',
    'San-Anselmo-DS2',
    'San-Anselmo-DS1',
    'Sausalito-E2',
    'Sausalito-ST-E2',
    'Sausalito-E1',
    'Sausalito-ST-E1',
    'Kentfield-2',
    'Kentfield-ST-2',
    'Kentfield-1',
    'Kentfield-ST-1',
    'Larkspur-2',
    'Larkspur-1',
    'Stinson-2',
    'Stinson-ST-2',
    'Stinson-1',
    'Stinson-ST-1',
    'Rift-Zone-26',
    'Rift-Zone-Jr-24',
    'Bayview-Trail-24',
    'Hidden-Canyon-20',
    'San-Quentin-24',
    'San-Quentin-20',
]

"""
DICT
"""

familyDict = {
    'Alpine Trail E2':'Alpine Trail E',
    'Alpine Trail E1':'Alpine Trail E',
    'Alpine Trail Carbon 2':'Alpine Trail',
    'Alpine Trail Carbon 1':'Alpine Trail',
    'Alpine Trail XR':'Alpine Trail',
    'Alpine Trail 7':'Alpine Trail',
    'Alpine Trail Carbon 2 Frame Kit':'Alpine Trail',
    'Rift Zone 29" Carbon XR':'Rift Zone 29',
    'Rift Zone 29" Carbon 2':'Rift Zone 29',
    'Rift Zone 29" Carbon 1':'Rift Zone 29',
    'Rift Zone 29" 3':'Rift Zone 29',
    'Rift Zone 29" 2':'Rift Zone 29',
    'Rift Zone 29" 1':'Rift Zone 29',
    'Rift Zone 29" Carbon XR Frame Kit':'Rift Zone 29',
    'Rift Zone 27.5" 3':'Rift Zone 27.5',
    'Rift Zone 27.5" 2':'Rift Zone 27.5',
    'Rift Zone 27.5" 1':'Rift Zone 27.5',
    'Rift Zone 26"':'Rift Zone 26\"Jr',
    'El Roy':'El Roy',
    'El Roy Frame Kit':'El Roy',
    'San Quentin 3':'San Quentin',
    'San Quentin 2':'San Quentin',
    'San Quentin 1':'San Quentin',
    'San Quentin 3 Frame Kit':'San Quentin',
    'Alcatraz':'Alcatraz',
    'Alcatraz Frame Kit':'Alcatraz',
    'Bolinas Ridge 2':'Bolinas Ridge',
    'Bolinas Ridge 1':'Bolinas Ridge',
    'Bobcat Trail 5':'Bobcat Trail',
    'Bobcat Trail 4':'Bobcat Trail',
    'Bobcat Trail 3':'Bobcat Trail',
    'Wildcat Trail 3':'Wildcat Trail',
    'Wildcat Trail 1':'Wildcat Trail',
    'Team Marin 2':'Team Marin',
    'Team Marin 1':'Team Marin',
    'Pine Mountain E2': 'Pine Mountain E',
    'Pine Mountain E1': 'Pine Mountain E',
    'Pine Mountain 2':'Pine Mountain',
    'Pine Mountain 1':'Pine Mountain',
    'Headlands 2':'Headlands',
    'Headlands 1':'Headlands',
    'Headlands Frame Kit':'Headlands',
    'Gestalt X11':'Gestalt',
    'Gestalt X10':'Gestalt',
    'Gestalt 2.5':'Gestalt',
    'Gestalt 2':'Gestalt',
    'Gestalt 1':'Gestalt',
    'Gestalt':'Gestalt',
    'DSX FS':'DSX',
    'DSX 2':'DSX',
    'DSX 1':'DSX',
    'DSX':'DSX',
    'Nicasio 2':'Nicasio',
    'Nicasio':'Nicasio',
    'Nicasio +':'Nicasio',
    'Lombard 1':'Lombard',
    'Four Corners':'Four Corners',
    'Muirwoods':'Muirwoods',
    'Muirwoods RC':'Muirwoods',
    'Presidio 3':'Presidio',
    'Presidio 2':'Presidio',
    'Presidio 1':'Presidio',
    'Fairfax 3':'Fairfax',
    'Fairfax 2':'Fairfax',
    'Fairfax ST 2':'Fairfax',
    'Fairfax 1':'Fairfax',
    'Fairfax ST 1':'Fairfax',
    'San Rafael DS2':'Dual Sport',
    'San Rafael DS1':'Dual Sport',
    'San Anselmo DS2':'Dual Sport',
    'San Anselmo DS1':'Dual Sport',
    'Sausalito 2':'Sausalito',
    'Sausalito ST 2':'Sausalito',
    'Sausalito 1':'Sausalito',
    'Sausalito ST 1':'Sausalito',
    'Kentfield 2':'Kentfield',
    'Kentfield ST 2':'Kentfield',
    'Kentfield 1':'Kentfield',
    'Kentfield ST 1':'Kentfield',
    'Larkspur 2':'Larkspur',
    'Larkspur 1':'Larkspur',
    'Stinson 2':'Stinson',
    'Stinson ST 2':'Stinson',
    'Stinson 1':'Stinson',
    'Stinson ST 1':'Stinson',
    #this needs to be created family
    'Stinson Electric':'Stinson E',
    #this needs to be created family
    'Stinson Electric ST':'Stinson E',
    'Rift Zone Jr 24"':'Rift Zone 26\"Jr',
    'Bayview Trail 24"':'Bayview Trail',
    'Hidden Canyon 20"':'Hidden Canyon',
    'San Quentin 24"':'San Quentin 24\"/20\"',
    'San Quentin 20"':'San Quentin 24\"/20\"',
    }

typeDict = {
    'Alpine Trail E2': 'eBikes',
    'Alpine Trail E1': 'eBikes',
    'Alpine Trail Carbon 2': 'Mountain',
    'Alpine Trail Carbon 1': 'Mountain',
    'Alpine Trail XR': 'Mountain',
    'Alpine Trail 7': 'Mountain',
    'Alpine Trail Carbon 2 Frame Kit': 'Mountain',
    'Rift Zone 29" Carbon XR': 'Mountain',
    'Rift Zone 29" Carbon 2': 'Mountain',
    'Rift Zone 29" Carbon 1': 'Mountain',
    'Rift Zone 29" 3': 'Mountain',
    'Rift Zone 29" 2': 'Mountain',
    'Rift Zone 29" 1': 'Mountain',
    'Rift Zone 29" Carbon XR Frame Kit': 'Mountain',
    'Rift Zone 27.5" 3': 'Mountain',
    'Rift Zone 27.5" 2': 'Mountain',
    'Rift Zone 27.5" 1': 'Mountain',
    'Rift Zone 26"': 'Youth/Kids',
    'El Roy': 'Mountain',
    'El Roy Frame Kit': 'Mountain',
    'San Quentin 3': 'Mountain',
    'San Quentin 2': 'Mountain',
    'San Quentin 1': 'Mountain',
    'San Quentin 3 Frame Kit': 'Mountain',
    'Alcatraz': 'Mountain',
    'Alcatraz Frame Kit': 'Mountain',
    'Bolinas Ridge 2': 'Mountain',
    'Bolinas Ridge 1': 'Mountain',
    'Bobcat Trail 5': 'Mountain',
    'Bobcat Trail 4': 'Mountain',
    'Bobcat Trail 3': 'Mountain',
    'Wildcat Trail 3': 'Mountain',
    'Wildcat Trail 1': 'Mountain',
    'Team Marin 2': 'Mountain',
    'Team Marin 1': 'Mountain',
    'Pine Mountain E2': 'eBikes',
    'Pine Mountain E1': 'eBikes',
    'Pine Mountain 2': 'Mountain',
    'Pine Mountain 1': 'Mountain',
    'Headlands 2': 'Drop Bar',
    'Headlands 1': 'Drop Bar',
    'Headlands Frame Kit': 'Drop Bar',
    'Gestalt X11': 'Drop Bar',
    'Gestalt X10': 'Drop Bar',
    'Gestalt 2.5': 'Drop Bar',
    'Gestalt 2': 'Drop Bar',
    'Gestalt 1': 'Drop Bar',
    'Gestalt': 'Drop Bar',
    'DSX FS': 'Fitness/Transit',
    'DSX 2': 'Fitness/Transit',
    'DSX 1': 'Fitness/Transit',
    'DSX': 'Fitness/Transit',
    'Nicasio 2': 'Drop Bar',
    'Nicasio': 'Drop Bar',
    'Nicasio +': 'Drop Bar',
    'Lombard 1': 'Fitness/Transit',
    'Four Corners': 'Drop Bar',
    'Muirwoods': 'Fitness/Transit',
    'Muirwoods RC': 'Fitness/Transit',
    'Presidio 3': 'Fitness/Transit',
    'Presidio 2': 'Fitness/Transit',
    'Presidio 1': 'Fitness/Transit',
    'Fairfax 3': 'Fitness/Transit',
    'Fairfax 2': 'Fitness/Transit',
    'Fairfax ST 2': 'Fitness/Transit',
    'Fairfax 1': 'Fitness/Transit',
    'Fairfax ST 1': 'Fitness/Transit',
    'San Rafael DS2': 'Fitness/Transit',
    'San Rafael DS1': 'Fitness/Transit',
    'San Anselmo DS2': 'Fitness/Transit',
    'San Anselmo DS1': 'Fitness/Transit',
    'Sausalito 2': 'eBikes',
    'Sausalito ST 2': 'eBikest',
    'Sausalito 1': 'eBikes',
    'Sausalito ST 1': 'eBikes',
    'Kentfield 2': 'Fitness/Transit',
    'Kentfield ST 2': 'Fitness/Transit',
    'Kentfield 1': 'Fitness/Transit',
    'Kentfield ST 1': 'Fitness/Transit',
    'Larkspur 2': 'Fitness/Transit',
    'Larkspur 1': 'Fitness/Transit',
    'Stinson 2': 'Fitness/Transit',
    'Stinson ST 2': 'Fitness/Transit',
    'Stinson 1': 'Fitness/Transit',
    'Stinson ST 1': 'Fitness/Transit',
    'Stinson Electric': 'eBikes',
    'Stinson Electric ST': 'eBikes',
    'Rift Zone Jr 24"': 'Youth/Kids',
    'Bayview Trail 24"': 'Youth/Kids',
    'Hidden Canyon 20"': 'Youth/Kids',
    'San Quentin 24"': 'Youth/Kids',
    'San Quentin 20"': 'Youth/Kids',
}

"""
UTIL
"""


#used for formatting other lists

"""
"""
for item in bikeList:
    print(f"regionCheck(\'{item}\', \'UK\', \'Australia\', \'Poland\', \'Czech\', \'Finland\', \'Spain\', \'Ecuador\', \'Canada\', \'International\', \'Germany\', \'Russia\', \'France\', \'Spanish\', \'India\', \'NZ\', \'Ukraine\')\n")



"""
for i in range(0,len(bikeListCopy)):
    print(f"slugT(\'{bikeListCopy[i]}\', \'2022-{bikeListCopy_Slugs[i].lower()}\')")


"""

#used for testing purposes
"""
print(familyDict['San Quentin 20\"'])
"""

#used for printing the length of lists
"""
test = 0
for item in bikeList:
    test += 1

print(test)
"""